-- ==========================================
-- MISSING TABLES
-- Sprint 21: three tables planned in earlier
-- sprints but never migrated.
-- ==========================================

-- ==========================================
-- USER_BLOCKS
-- Planned Sprint 9. Users can block others.
-- Blocked users cannot see each other's posts,
-- profiles, or initiate DMs. This table is the
-- source of truth — RLS policies query it.
-- ==========================================

CREATE TABLE IF NOT EXISTS public.user_blocks (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blocker_id  UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  blocked_id  UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT user_blocks_unique UNIQUE (blocker_id, blocked_id),
  CONSTRAINT user_blocks_no_self CHECK (blocker_id != blocked_id)
);

COMMENT ON TABLE public.user_blocks IS 'Directional block relationship. If A blocks B, B cannot see A in feeds, member lists, or DMs.';

ALTER TABLE public.user_blocks ENABLE ROW LEVEL SECURITY;

-- Blocker can see, create, and remove their own blocks
CREATE POLICY "blocks_select_own"  ON public.user_blocks FOR SELECT USING (auth.uid() = blocker_id);
CREATE POLICY "blocks_insert_own"  ON public.user_blocks FOR INSERT WITH CHECK (auth.uid() = blocker_id);
CREATE POLICY "blocks_delete_own"  ON public.user_blocks FOR DELETE USING (auth.uid() = blocker_id);

-- Fast lookup by either party
CREATE INDEX IF NOT EXISTS idx_user_blocks_blocker ON public.user_blocks (blocker_id);
CREATE INDEX IF NOT EXISTS idx_user_blocks_blocked ON public.user_blocks (blocked_id);

-- ==========================================
-- GROMADA_INVITES
-- Planned Sprint 10. Elders generate a
-- one-time invite link. The app deep-links to
-- polana://invite/<code> which calls the
-- accept-invite Edge Function.
-- ==========================================

CREATE TABLE IF NOT EXISTS public.gromada_invites (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  gromada_id  UUID        NOT NULL REFERENCES public.gromady(id) ON DELETE CASCADE,
  created_by  UUID        NOT NULL REFERENCES public.profiles(id),
  -- URL-safe random code, e.g. "xK9mP2qR"
  code        TEXT        NOT NULL UNIQUE,
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '7 days'),
  used_by     UUID        REFERENCES public.profiles(id),
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.gromada_invites IS 'Single-use invite codes generated by gromada elders. Expires after 7 days.';

ALTER TABLE public.gromada_invites ENABLE ROW LEVEL SECURITY;

-- Any authenticated user can look up an invite by code (needed to show
-- the "you've been invited to X gromada" screen before accepting)
CREATE POLICY "invites_select_any_authenticated" ON public.gromada_invites
  FOR SELECT USING (auth.uid() IS NOT NULL);

-- Only the elder of the gromada can create invites
CREATE POLICY "invites_insert_elder" ON public.gromada_invites
  FOR INSERT WITH CHECK (
    auth.uid() = created_by AND
    EXISTS (
      SELECT 1 FROM public.gromady
       WHERE id = gromada_invites.gromada_id
         AND elder_id = auth.uid()
    )
  );

-- Invite redemption (used_by / used_at) goes through service role
-- in the accept-invite Edge Function — no client UPDATE policy needed.

CREATE INDEX IF NOT EXISTS idx_invites_code       ON public.gromada_invites (code);
CREATE INDEX IF NOT EXISTS idx_invites_gromada_id ON public.gromada_invites (gromada_id);
CREATE INDEX IF NOT EXISTS idx_invites_expires_at ON public.gromada_invites (expires_at)
  WHERE used_by IS NULL;

-- Trigger: automatically reject single-use codes that have already been used
CREATE OR REPLACE FUNCTION enforce_single_use_invite()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.used_by IS NOT NULL THEN
    RAISE EXCEPTION 'Invite code % has already been used', OLD.code;
  END IF;
  IF OLD.expires_at < NOW() THEN
    RAISE EXCEPTION 'Invite code % has expired', OLD.code;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Only fire when used_by is being set (i.e. redemption update)
CREATE TRIGGER enforce_single_use_invite
  BEFORE UPDATE OF used_by ON public.gromada_invites
  FOR EACH ROW
  WHEN (NEW.used_by IS NOT NULL AND OLD.used_by IS NULL)
  EXECUTE FUNCTION enforce_single_use_invite();

-- ==========================================
-- ADMIN_USERS
-- Used by both Sprint 21 (Edge Function auth)
-- and Sprint 22 (admin panel login guard).
-- Role hierarchy:
--   super_admin    — full access to everything
--   moderator      — can resolve reports, ban users
--   content_editor — can edit interests, names, event types
-- ==========================================

CREATE TABLE IF NOT EXISTS public.admin_users (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  role        TEXT NOT NULL DEFAULT 'moderator'
                CHECK (role IN ('super_admin', 'moderator', 'content_editor')),
  granted_by  UUID REFERENCES public.profiles(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at  TIMESTAMPTZ  -- soft-delete; NULL = active
);

COMMENT ON TABLE public.admin_users IS 'Admin panel access control. Mutations only via service role (Edge Function admin-grant-access). Never writable from client.';

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Admins can see their own record (needed for role check in admin panel middleware)
CREATE POLICY "admin_users_select_own" ON public.admin_users
  FOR SELECT USING (auth.uid() = user_id AND revoked_at IS NULL);

-- No INSERT/UPDATE/DELETE policies — service role only.
-- This means the admin panel CANNOT grant/revoke access from the browser;
-- it MUST go through an Edge Function that validates the caller is a super_admin.

CREATE INDEX IF NOT EXISTS idx_admin_users_user_id ON public.admin_users (user_id)
  WHERE revoked_at IS NULL;

-- ==========================================
-- API_RATE_LIMITS
-- Sliding-window counter for Edge Function
-- rate limiting (Sprint 21 s21-edge-security).
-- Keyed by (user_id, endpoint, window_start).
-- ==========================================

CREATE TABLE IF NOT EXISTS public.api_rate_limits (
  id           BIGSERIAL   PRIMARY KEY,
  user_id      UUID        NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  endpoint     TEXT        NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  request_count INT        NOT NULL DEFAULT 1,
  CONSTRAINT api_rate_limits_unique UNIQUE (user_id, endpoint, window_start)
);

COMMENT ON TABLE public.api_rate_limits IS 'Sliding 1-minute window request counter per user per Edge Function endpoint. Pruned by pg_cron hourly.';

ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;
-- No client access — only writable/readable via service role in Edge Functions.

CREATE INDEX IF NOT EXISTS idx_rate_limits_lookup
  ON public.api_rate_limits (user_id, endpoint, window_start DESC);

-- Prune old rate limit windows hourly via pg_cron (added in scalability migration)
